### ISSUE TITLE
Realtime-compiled apply kernels

### ISSUE THREAD

**Issue by szagoruyko** [hughperkins/cltorch#2]
Hi Hugh,
I noticed you have "Original, not in torch or cutorch" section with apply kernels, but in fact we have them in https://github.com/szagoruyko/cutorch-rtc for CUDA 7. It would be nice to keep the same syntax in cltorch.

**Comment by hughperkins** [comment]
Ah, interesting :-)  Thanks! :-)  Will take a look.

**Comment by hughperkins** [comment]
Hi. Added an 'update' note linking to cutorch-rtc.  I guess we think that same way :-)  Ok if I close the issue for now?

**Comment by szagoruyko** [comment]
no I mean the syntax is different right now.

| cutorch-rtc | cltorch |
| --- | --- |
| apply | apply |
| apply2 | map |
| apply3 | map2 |

and variables in cutorch-rtc `x`, `y` and `z`, cltorch `*in`, `*out` etc.
would be nice to have the same syntax

**Comment by hughperkins** [comment]
Yes, you are right.  But I think my funciton names match better with the torch naming convention, whereas your function names are more original, though logical.

For the parameter names, I kind of agree that `*out` and `*in1` are pretty dumb names, from inside lua, and I might change mine to match yours.

**Comment by hughperkins** [comment]
I've added apply2 and apply3 as synonyms of map and map2.

I plan to do a search and replace later, to change 'x' to '*out' and so on, so that code written for your library will work on mine too.

**Comment by hughperkins** [comment]
Ok, I added the search and replace, so code that works on your library will run ok on cltorch now.

**Comment by szagoruyko** [comment]
Nice, thanks! it looks pretty cool now, one could write nn library that would be realtime compiled to OpenCL or CUDA :)
Btw does cltorch support CPU?
One thing that I often do with OpenCL is writing kernels directly in lua with this http://colberg.org/lua-opencl/ , do you maybe have something like compile + launchPTX from cutorch-rtc? I mean you give a kernel, it compiles it and you run it with a list of arguments which are scalars or tensors

**Comment by hughperkins** [comment]
> Nice, thanks! it looks pretty cool now

Cool.  Good! :-)

> One thing that I often do with OpenCL is writing kernels directly in lua with this http://colberg.org/lua-opencl/ , do you maybe have something like compile + launchPTX from cutorch-rtc? I mean you give a kernel, it compiles it and you run it with a list of arguments which are scalars or tensors

Hmmm, that should be pretty easy to do.  Can you define how you would like the interface for that to look please?  I'll give you some background about how the kernels are built and stuff, which will help to design an appropriate api.  Conceptually:
- all kernel source code is compiled at runtime
- many of the kernels are generated at runtime, from Lua templates
- obviously, for the generated ones, we dont want to regenerate each kernel launch, so we create a unique name, based on the generation parameters, which we use to store the compiled kernel, so that we can look it up next time

You can for example that the kernel for Apply3 has the apply operation provided as a templated parameter, [Apply3.cl#48](https://github.com/hughperkins/cltorch/blob/master/lib/THCl/THClApply.cl#L48)
```
void op( global float *out, global float *in1, global float *in2 ) { // simplifying this a bit, you have a link to the real source just above
    {{operation}};
}

```
- those bits in `{{` `}}` will be replaced at compilation value by the value of the variable inside it, ie `operation`, which will be here eg `*out = *in1 + *in2`, or similar

Since we want different operations to use different kernels, since the operation is different, so we put the operation inside the unique generated name, eg for Apply3, this looks like [THClApply.h#176](https://github.com/hughperkins/cltorch/blob/master/lib/THCl/THClApply.h#L176):
```
std::string uniqueName = "THClApply_3t" + easycl::toString(numScalars) + "s_" + easycl::toString(A) + "_" + easycl::toString(B) + "_" + easycl::toString(C) + "_" + op->operator3();
```
- you can see that we are using the name of the kernel, the number of dimensions for each tensor, and the actual operation, ie `op->operator3()`, which will be for example `*out = *in1 + *in2`, in order to generate the unique name

We can see also where the operation is passed to the kernel templater, [THClApply.h#205](https://github.com/hughperkins/cltorch/blob/master/lib/THCl/THClApply.h#L205)
```
  kernelBuilder.set("operation", op->operator3());
```

Finally, when we want to launch a kernel, we:
- generate an appropriate unique name
- check to see if we've already compiled a kernel with that name
- if we have, then reuse that
- otherwise build it, passing in the appropriate parameters to the template builder
In code this looks like, [THClGather.cpp#L50](https://github.com/hughperkins/cltorch/blob/master/lib/THCl/THClGather.cpp#L50):
```
  std::string uniqueName = __FILE__ ":gather:" + easycl::toString(nDims);
  EasyCL *cl = THClState_getCl(state);
  CLKernel *kernel = 0;
  if(cl->kernelExists(uniqueName)) {
    kernel = cl->getKernel(uniqueName);
  } else {
    TemplatedKernel kernelBuilder( THClState_getCl(state) );
    // ... build kernel here
  }
```

Now, in the case of Apply and Reduce and so on, the template contains merely a small string, that is substituted for different operations, and added to the unique name.  In your case, since you want to supply an entire kernel, it might not make sense to use the entire kernel as the lookup string.  You might want to need to provide the lookup name yourself, as one of the parameters in your api call.  Similarly, in fact you might choose to entirely forego the templating process, since you can handle that in your lua code right?, and simply pass the kernel code directly to the opencl compiler, as-is.

Next, you mention parameters.... parameters can be easy or hard, depending on how general you want this to be, I suppose :-P  The simply way would be to start with kernels with a well-defined declaration, eg receiving exactly 1 tensor, and nothing else, and then you can generalize?  For one tensor, hmmm, I noticed I started changing to writing this as though you will implement this :-P  Perhaps you will, or perhaps your api definition will be such that by the time we've discussed this, it's easy for me to implement, and suits your requirements.  Either way is fine I suppose :-)  So, whoever implements it, initially, the kernel would probably be hard-coded, I mean, your provided kernel would need to comply with, a standard interface looking something like:
```
kernel void(global TensorInfoCl *self_info, global float *self_data ) {
```

I think that an appropriate model actually is not Apply, since that code is really complicated, and convoluted, in my opinion.  At least, it includes `THClReduceApplyUtils.cl`, which is really long.  If you look at the kernel for gather, that's quite a lot simpler, and reflects exactly the style of API I suggest above, [THClGather.cl#L10](https://github.com/hughperkins/cltorch/blob/master/lib/THCl/THClGather.cl#L10)
```
kernel void THClTensor_kernel_gather(
    global TensorInfoCl *dst_info, global float*dst_data,
    global const TensorInfoCl *src_info, global float*src_data,
   int dim,
    global const TensorInfoCl *idx_info, global float*idx_data,
   int totalElements
)
{
  // ... code here
}
```
This kernel receives three tensors.  Each tensor is provided as a pair of TensorInfoCl structs, and float *data.  The offset is in the struct.  The struct needs to be provided in the kernel, ie [THClGather.cl#L3](https://github.com/hughperkins/cltorch/blob/master/lib/THCl/THClGather.cl#L3)
```
typedef struct TensorInfoCl {
  unsigned int sizes[{{MAX_CLTORCH_DIMS}}];
  unsigned int strides[{{MAX_CLTORCH_DIMS}}];
  int offset;
  int dims;
} TensorInfoCl;
```
Hmmm, and you need to provide MAX_CLTORCH_DIMS to the templater, or hard-code this.  Either ok.

Then you can see that the parameters are simply provided to the kernel [here](https://github.com/hughperkins/cltorch/blob/master/lib/THCl/THClGather.cpp#L76).
```
  THClKernels k(state, kernel);
  kernel->in(1, &selfInfoCl);
  kernel->out(self->storage->wrapper);
  kernel->in(1, &srcInfoCl);
  kernel->in(src->storage->wrapper);
  k.in((int)dim);
  kernel->in(1, &indexInfoCl);
  kernel->in(index->storage->wrapper);
  k.in( (int)totalElements );
```
You also need to briefly consider what grid and block dimensions are needed.  If you're doing a simple `apply` type kernel, with no local memory, or thread inter-dependencies, then you could simply accept any layout in fact, ie the same one used in apply or reduce.  Later, if you wanted more general kernels, you could add a `grid` and `block` parameter to your API.  (or call it globalSize and workgroupSize, either ok with me... just using grid and block is more consistent with the existing cutorch naming, which came from CUDA).

Once you've decided on grid and block, running the kernel is easy:
```
 k.run(grid, block);
```

**Comment by hughperkins** [comment]
Hmmm, should we open a new issue for adding whole-kernel api?  Then it would a. be consistent with the title b. be visible to other people
